Cache/MemoryCache/Pages/CacheDependencies.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Primitives;

namespace MemoryCache.Pages
{
    public class CacheDependenciesModel : PageModel
    {
        private readonly IMemoryCache cache;

        public CacheDependenciesModel(IMemoryCache cache)
        {
            this.cache = cache;
        }    

        public void OnGet()
        {
            var cts = new CancellationTokenSource();
            cache.Set("cts", cts);

            MemoryCacheEntryOptions options = new MemoryCacheEntryOptions();
            options.AddExpirationToken(new CancellationChangeToken(cts.Token));

            cache.Set<string>("parentKey", DateTime.Now.ToString(), options);

            cache.Set<string>("ChildKey1", "Child1 value", new CancellationChangeToken(cts.Token));
            cache.Set<string>("ChildKey2", "Child2 value", new CancellationChangeToken(cts.Token));
        }
    }
}

Cache/MemoryCache/Pages/DemoCache.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MemoryCache.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace MemoryCache.Pages
{
    public class DemoCacheModel : PageModel
    {
        private readonly IMemoryCache cache;
        public string TimeCache { get; set; }

        public List<User> Users { get; set; }

        public DemoCacheModel(IMemoryCache cache)
        {
            this.cache = cache;
        }

        public void OnGet()
        {
            TimeCache = cache.Get<string>("timeCache");

            Users = cache.Get<List<User>>("ListUser");
        }
    }
}

Cache/MemoryCache/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MemoryCache.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Cache/MemoryCache/Pages/Index.cshtml.cs
using MemoryCache.Model;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading;

namespace MemoryCache.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private IMemoryCache cache;

        public IndexModel(ILogger<IndexModel> logger, IMemoryCache cache)
        {
            _logger = logger;
            this.cache = cache;
        }

        public void OnGet()
        {
            cache.Set<string>("timeCache", DateTime.Now.ToString());

            if (!cache.TryGetValue<string>("timeCache", out string timeCache))
            {
                ViewData["ExistingCache"] = "Cache với key: timeCache không tồn tại";
                cache.Set<string>("timeCache", DateTime.Now.ToString());
            }
            else
            {
                ViewData["ExistingCache"] = $"Cache với key: timeCache đã tồn tại với value: {timeCache}";
            }

            //Set cache for complex data
            var listUserCached = new List<User>();
            if (!cache.TryGetValue<List<User>>("ListUser", out listUserCached))
            {
                var listUser = new List<User>()
                {
                    new User
                    {
                        Id = 1,
                        Name = "Iron man"
                    },
                    new User
                    {
                        Id = 2,
                        Name = "Spider man"
                    }
                };
                cache.Set<List<User>>("ListUser", listUser);
            }


            var timeCacheGetOrCreate = cache.GetOrCreate<string>("timeCacheGetOrCreate", entry =>
            {
                return DateTime.Now.ToString();
            });

            ViewData["timeCacheGetOrCreate"] = timeCacheGetOrCreate;

            ViewData["expiredCache"] = cache.Get<string>("expiredCache");

            ViewData["callbackMessage"] = cache.Get<string>("callbackMessage");

            ViewData["parentKey"] = cache.Get<string>("parentKey");
            ViewData["ChildKey1"] = cache.Get<string>("ChildKey1");
            ViewData["ChildKey2"] = cache.Get<string>("ChildKey2");
        }

        //Remove dependences cache
        public void OnPostRemoveDependencesCache()
        {
            CancellationTokenSource cts =
                cache.Get<CancellationTokenSource>("cts");
            cts.Cancel();
        }
    }
}

Cache/MemoryCache/Pages/MemoryCacheEntryOptions.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using System;

namespace MemoryCache.Pages
{
    public class MemoryCacheEntryOptionsModel : PageModel
    {
        private readonly IMemoryCache cache;

        public MemoryCacheEntryOptionsModel(IMemoryCache cache)
        {
            this.cache = cache;
        }

        public void OnGet()
        {
            MemoryCacheEntryOptions options = new MemoryCacheEntryOptions();

            //cache se het han sau 2 phut tu thoi diem hien tai
            options.AbsoluteExpiration = DateTime.Now.AddMinutes(2);

            //cache se het han sau 1 phut neu khong duoc truy cap, ke ca con thoi han cua AbsoluteExpiration
            options.SlidingExpiration = TimeSpan.FromMinutes(1);

            //Low, Normal, High và NeverRemove => cache sẽ xóa dựa vào độ ưu tiên từ thấp đến cao. Nerver remove không bao h xóa
            options.Priority = CacheItemPriority.Normal;

            // Callback when cached item is removed
            options.RegisterPostEvictionCallback(EvictionCallback, this);

            cache.Set<string>("expiredCache", DateTime.Now.ToString(), options);
        }

        private static void EvictionCallback(object key, object value, EvictionReason reason, object state)
        {
            var message = $"Entry was evicted. Reason: {reason}.";
            ((MemoryCacheEntryOptionsModel)state).cache.Set("callbackMessage", message);
        }
    }
}

Cache/MemoryCache/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MemoryCache.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Cache/MemoryCache/Pages/CacheDependencies.cshtml
@page
@model MemoryCache.Pages.CacheDependenciesModel
@{
}

<h1>Go to page to create cache</h1>

Cache/MemoryCache/Pages/DemoCache.cshtml
@page
@model MemoryCache.Pages.DemoCacheModel
@{
}


<h1>TimeCache: @Model.TimeCache</h1>


<h1>List user cache</h1>
@foreach(var user in Model.Users)
{
    <ul>
        <li>@user.Name</li>
    </ul>
}

Cache/MemoryCache/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <h2>GetOrCreate: @ViewData["timeCacheGetOrCreate"] </h2>

    @if (!string.IsNullOrWhiteSpace(@ViewData["expiredCache"]?.ToString()))
    {
        <h2>MemoryCacheEntryOption: @ViewData["expiredCache"]</h2>
    }


    <h2>@ViewData["callbackMessage"]</h2>

    <h1>Cache dependences</h1>
    <h2>Parent cache: @ViewData["parentKey"]</h2>
    <h2>Child 1 cache: @ViewData["ChildKey1"]</h2>
    <h2>Child 2 cache: @ViewData["ChildKey2"]</h2>

    <form asp-page-handler="RemoveDependencesCache">
        <div class="control-group form-group">
            <input type="submit" class="btn btn-success" value="Remove dependence cache" />
        </div>
    </form>
</div>

Cache/MemoryCache/Pages/MemoryCacheEntryOptions.cshtml
@page
@model MemoryCache.Pages.MemoryCacheEntryOptionsModel
@{
}

<h1>Go to page to create cache</h1>

Cache/MemoryCache/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MemoryCache</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MemoryCache</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/DemoCache">Demo cache</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/MemoryCacheEntryOptions">MemoryCacheEntryOptions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/CacheDependencies">CacheDependencies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MemoryCache - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>